version: '3.8'

services:
  blef-client:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: blef-client
    ports:
      - "5678:5678"

  blef-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: blef-server
    ports:
      - "5173:5173"
