services:
  blef-client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        API_URL: "http://localhost:5678" 
    image: matid90/ebiznesdocker:blefclient
    ports:
      - "80:80"

  blef-server:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        CLIENT_URL: "http://localhost" 
    image: matid90/ebiznesdocker:blefserver
    ports:
      - "5678:5678"
