export enum SocketEvents {
    createGameToServer = 'createGameToServer',
    createGameToHost = 'createGameToHost',
    joinGameToServer = 'joinGameToServer',
    joinGameToClient = 'joinGameToClient',
    newPlayerJoinedGameToHost = 'newPlayerJoinedGameToHost',
    newPlayerJoinedGameToClient = 'newPlayerJoinedGameToClient',
    playerLeftGameToServer = 'playerLeftGameToServer',
    playerLeftGameToPlayers = 'playerLeftGameToPlayers',
    hitToHost = 'hitToHost',
    hitToServer = 'hitToServer',
    checkToHost = 'checkToHost',
    checkToServer = 'checkToServer',
    gameUpdateNextPlayerToClient = 'gameUpdateNextPlayerToClient',
    gameUpdateEndOfRoundAndStartOfNewRountToCLient = 'gameUpdateEndOfRoundAndStartOfNewRountToCLient',
    startGameToServer = 'startGameToServer',
    startGameToClients = 'startGameToClients',
    startGameToHost = 'startGameToHost',
    gameClosedToServer = 'gameClosedToServer',
}
