name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        registry: blefacr-ajc0eha4cua2e6dk.azurecr.io

    - name: Build and push backend Docker image
      run: |
        docker build -t blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-server:latest --build-arg CLIENT_URL=https://blef-client.thankfulwater-59edc31b.polandcentral.azurecontainerapps.io -f server/Dockerfile .
        docker push blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-server:latest

    - name: Build and push frontend Docker image
      run: |
        docker build -t blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-client:latest --build-arg API_URL=https://blef-server.thankfulwater-59edc31b.polandcentral.azurecontainerapps.io -f client/Dockerfile .
        docker push blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy backend app to Azure Container Apps
      run: |
        az containerapp update \
          --name blef-server \
          --resource-group blef \
          --image blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-server:latest \

    - name: Deploy frontend app to Azure Container Apps
      run: |
        az containerapp update \
          --name blef-client \
          --resource-group <resource-group-name> \
          --image blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-client:latest \
