name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
        registry: blefacr-ajc0eha4cua2e6dk.azurecr.io

    - name: Build and push backend Docker image
      run: |
        docker build -t blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-server:latest --build-arg CLIENT_URL=https://blef-game-aaf0egamftgyecar.westeurope-01.azurewebsites.net -f server/Dockerfile .
        docker push blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-server:latest

    - name: Build and push frontend Docker image
      run: |
        docker build -t blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-client:latest --build-arg API_URL=blef-server-c9c5bkhrdpb7gtbg.polandcentral-01.azurewebsites.net -f client/Dockerfile .
        docker push blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-client:latest

    - name: Deploy backend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_BACKEND_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_BACKEND_WEBAPP_PUBLISH_PROFILE }}
        images: blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-server:latest

    - name: Deploy frontend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_FRONTEND_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FRONTEND_WEBAPP_PUBLISH_PROFILE }}
        images: blefacr-ajc0eha4cua2e6dk.azurecr.io/blef-client:latest
  notify:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Send deployment notification email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_HOST }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Deployment Completed Successfully
          to: ${{ secrets.SUBSCRIBER_MAIL }}
          from: ${{ secrets.SENDER_MAIL }}
          body: |
            The deployment of blef-game to Azure Web Apps has finished successfully.